### ISSUE TITLE
[BUG] L.markerClusterGroup is not a function

### ISSUE THREAD

**Issue by peixotoleonardo** [marcopollivier/techagenda#3]
# Descrição

Ao carregar a página, no console da aplicação aparece que a função markerClusterGroup não é um função, provavelmente por isso o layout da página está quebrando.

![image](https://github.com/marcopollivier/techagenda/assets/67864816/4f468f81-9e7a-4986-80dc-9d8935c9ec8b)

**Comment by marcopollivier** [comment]
hmm não tinha reparado isso. Vou dar uma olhada aqui pra ver se depois que corrigiram o bug do mapa essa mensagem sumiu também.

**Comment by marcopollivier** [comment]
Corrigido. tava faltando um import. Agora tá até marcando certinho os locais de eventos
